### PR TITLE
Update GA and meta info for site

### LINKED ISSUE #18: Add seAp Analytics
## Description
We need to add analytics to assess the usage of the site for the project

## Plan
- [x] @roseb04 to agree with seAp how we are going to implement analytics
- [x] Add script to site
- [x] Add fresh index files

## Acceptance Criteria
- [ ] Google Analytics works when users accept the GA cookie
- [ ] GA registers on page load
- [ ] Site title relates to seAp

### PR DESCRIPTION
**Pull request by rosejbon**
Fixes #18 

## Description

- Updated the UA identifier for the site to connect to the GA account we have set up
- Identifier = UA-157133795-1

@neontribe/ca-seap

### CODE REVIEW

**Review by AlinChindea — CHANGES_REQUESTED** [review]
in `index.html`, the `script` tag starting on line 30, needs another line before the closing `</script>`. it should look like this: 
```
<script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        
        gtag('config', 'UA-157133795-1');
 </script>
```
You're missing this line `gtag('config', 'UA-157133795-1');`

**Comment by rosejbon** [comment]
> in `index.html`, the `script` tag starting on line 30, needs another line before the closing `</script>`. it should look like this:
> 
> ```
> <script>
>         window.dataLayer = window.dataLayer || [];
>         function gtag(){dataLayer.push(arguments);}
>         gtag('js', new Date());
>         
>         gtag('config', 'UA-157133795-1');
>  </script>
> ```
> 
> You're missing this line `gtag('config', 'UA-157133795-1');`

Thanks @AlinChindea I've made that amendment

**Review by AlinChindea — APPROVED** [review]
:shipit: Aces!

**Comment by katjam** [comment]
@AlinChindea - note that I approved your branding commit. :+1:

**Comment by AlinChindea** [comment]
@katjam do we need to redeploy to staging for Karl to test this issue?

**Comment by katjam** [comment]
Yes - shall I deploy now or wait on other fixes?

**Comment by AlinChindea** [comment]
there might be browser-related issues but we'll only get to those next week I think. Also, check my question in slack contemplating_action channel - about the stories thumbnails and images. it seems these are missing from staging and I definitely added those so this requires a deploy to allow Karl proper testing

**Pull request merged**
