### PR TITLE
Fixed grammatical error

### LINKED ISSUE #51: Double "the" in footer
## Description
"The The Advocacy..." should be "The Advocacy..." in the footer.

### PR DESCRIPTION
**Pull request by j-gynn**
Fixes #51 

## Description

- 
-

@neontribe/ca-seap

### CODE REVIEW

**Comment by katjam** [comment]
@RabidGamer This looks good - but next time hang on until someone has reviewed it. :1st_place_medal:

**Comment by katjam** [comment]
@roseb04 Check this then tag and ship I guess.

**Comment by rosejbon** [comment]
Looks good to me, thanks @RabidGamer

**Comment by Nikomus** [comment]
Should it be "The Advocacy People's service"?

**Comment by AlinChindea** [comment]
Can we enable required reviews for pull requests? [https://help.github.com/en/github/administering-a-repository/enabling-required-reviews-for-pull-requests](https://help.github.com/en/github/administering-a-repository/enabling-required-reviews-for-pull-requests)

@roseb04 perhaps this is something we can do better and be included in your report :-)

**Comment by j-gynn** [comment]
Oh! My bad! I assumed that, since reviews weren't required, I didn't need to wait for one. My apologies! I'll assume in future that reviews are ALWAYS required, regardless of whether GitHub lets me merge or not. Good to know!

**Comment by katjam** [comment]
No problem. Is totally our fault. That sounds a good tactic though.

**Pull request merged**
